{
 "title": "Cluster Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "application" },
   {
    "name": "namespace",
    "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container_name!=\"POD\"},namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",container_name!=\"POD\"},pod_name)"
   },
   {
    "name": "container",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~\"$pod\",container_name!=\"POD\"},container_name)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Monthly Cost",
   "type": "singlestat",
   "description": "Expected monthly cost given current CPU, memory storage, and network resource consumption",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "# CPU\nsum(\n (\n (\n sum(kube_node_status_capacity_cpu_cores) by (node)\n * on (node) group_left (label_cloud_google_com_gke_preemptible)\n kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"}\n ) * $costpcpu\n )\n or\n (\n (\n sum(kube_node_status_capacity_cpu_cores) by (node)\n * on (node) group_left (label_cloud_google_com_gke_preemptible)\n kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"}\n ) * ($costcpu - ($costcpu / 100 * $costDiscount))\n )\n) \n\n+ \n\n# Storage\nsum (\n sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace) or up * 0\n) / 1024 / 1024 /1024 * $costStorageSSD\n\n+\n\nsum (\n sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace) or up * 0\n) / 1024 / 1024 /1024 * $costStorageStandard\n\n+ \n\nsum(container_fs_limit_bytes{id=\"/\"}) / 1024 / 1024 / 1024 * 1.03 * $costStorageStandard \n\n+\n\n# END STORAGE\n# RAM \nsum(\n (\n (\n sum(kube_node_status_capacity_memory_bytes) by (node)\n * on (node) group_left (label_cloud_google_com_gke_preemptible)\n kube_node_labels{label_cloud_google_com_gke_preemptible=\"true\"}\n ) /1024/1024/1024 * $costpram\n )\n or\n (\n (\n sum(kube_node_status_capacity_memory_bytes) by (node)\n * on (node) group_left (label_cloud_google_com_gke_preemptible)\n kube_node_labels{label_cloud_google_com_gke_preemptible!=\"true\"}\n ) /1024/1024/1024 * ($costram - ($costram / 100 * $costDiscount))\n)\n)\n\n+\n\n#Network \nSUM(rate(node_network_transmit_bytes_total{device=\"eth0\"}[60m]) / 1024 / 1024 / 1024 ) * (60 * 60 * 24 * 30) * $costEgress",
     "legendFormat": " {{ node }}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})"
    }
   ]
  },
  {
   "title": "Node composition",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select instanceType,region,contract from nodetype..nodetype group by federation,cluster, nodeName limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Cluster Health Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-apiservers\"} == 1) / count(up{job=\"kubernetes-apiservers\"})) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum by(instance) (rate(apiserver_request_count[5m]))) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Error Rates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum by(instance) (rate(apiserver_request_count[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "min",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-nodes\"} == 1) / count(up{job=\"kubernetes-nodes\"})) * 100"
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "format": "percent",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) * 100 / sum(kube_node_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)  / count(up{job=\"kubernetes-nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"}) * 100 / sum(kube_node_status_condition{condition=\"MemoryPressure\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}) * 100 / sum(kube_node_status_condition{condition=\"DiskPressure\"})"
    }
   ]
  },
  {
   "title": "Crashing Control Plane Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{namespace=~\"kube-system\"}[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Crashing Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total[1h]) > 3)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(\n sum(\n count(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n * on (instance) \n sum(irate(container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (instance)\n ) \n / \n (sum (kube_node_status_allocatable_cpu_cores))\n) * 100"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(container_memory_usage_bytes{container_name!=\"\"}) / SUM(kube_node_status_allocatable_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Storage Usage (exclude SSD)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (\n sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kubelet_volume_stats_used_bytes) by (persistentvolumeclaim, namespace) or\n + sum(container_fs_usage_bytes{device=~\"^/dev/[svx]+d[a-z][1-9]$\",id=\"/\"})\n) /\nsum (\n sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace) or\n + sum(container_fs_limit_bytes{device=~\"^/dev/[svx]+d[a-z][1-9]$\",id=\"/\"})\n) * 100"
    }
   ]
  },
  {
   "title": "SSD Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (\n sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kubelet_volume_stats_used_bytes) by (persistentvolumeclaim, namespace)\n) /\nsum (\n sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace)\n) * 100"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=\"/\",instance=\"$node\"}[10m])) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(container_memory_usage_bytes{container_name!=\"\",pod_name!=\"\",instance=\"$node\"}) * 100 / SUM(kube_node_status_allocatable_memory_bytes{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "Storage Usage (exclude SSD)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (\n sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*\",instance=\"$node\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kubelet_volume_stats_used_bytes{instance=\"$node\"}) by (persistentvolumeclaim, namespace) or\n + sum(container_fs_usage_bytes{device=~\"^/dev/[svx]+d[a-z][1-9]$\",id=\"/\",instance=\"$node\"})\n) /\nsum (\n sum(kube_persistentvolumeclaim_info{storageclass!~\".*ssd.*\",instance=\"$node\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{instance=\"$node\"}) by (persistentvolumeclaim, namespace) or\n + sum(container_fs_limit_bytes{device=~\"^/dev/[svx]+d[a-z][1-9]$\",id=\"/\",instance=\"$node\"})\n) * 100"
    }
   ]
  },
  {
   "title": "SSD Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (\n sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*\",instance=\"$node\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kubelet_volume_stats_used_bytes{instance=\"$node\"}) by (persistentvolumeclaim, namespace) \n) /\nsum (\n sum(kube_persistentvolumeclaim_info{storageclass=~\".*ssd.*\",instance=\"$node\"}) by (persistentvolumeclaim, namespace, storageclass)\n + on (persistentvolumeclaim, namespace) group_right(storageclass)\n sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{instance=\"$node\"}) by (persistentvolumeclaim, namespace) \n) * 100"
    }
   ]
  },
  {
   "title": "Current pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"\",container_name!=\"POD\",pod_name!=\"\",instance=\"$node\"}[10m])) by (pod_name)"
    },
    {
     "expr": "sum(label_replace(\nsum(avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"\",container!=\"POD\",node=\"$node\"}[10m])) by (pod), \n\"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)"
    },
    {
     "expr": "sum(label_replace(\nsum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"\",container!=\"POD\",node=\"$node\"}[10m])) by (pod), \n\"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)"
    },
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes{container_name!=\"\",container_name!=\"POD\",pod_name!=\"\",instance=\"$node\"}[10m])) by (pod_name)\n"
    },
    {
     "expr": "sum(label_replace(label_replace(\nsum(avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"\",container!=\"POD\",node=\"$node\"}[10m])) by (pod),\n\"container_name\",\"$1\",\"container\",\"(.+)\"), \"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)\n"
    },
    {
     "expr": "sum(label_replace(label_replace(\nsum(avg_over_time(kube_pod_container_resource_limits_memory_bytes{container!=\"\",container!=\"POD\",node=\"$node\"}[10m])) by (pod),\n\"container_name\",\"$1\",\"container\",\"(.+)\"), \"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)\n"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(\r\n count(label_replace(\r\n   avg_over_time(container_cpu_usage_seconds_total{container_name!=\"\",container_name!=\"POD\",pod_name!=\"\",instance=\"$node\"}[1h])\r\n     ,\"pod\",\"$1\",\"pod_name\",\"(.+)\")\r\n ) \r\n by (pod)\r\n)"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 26 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "singlestat",
   "description": "number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_node_status_capacity_cpu_cores{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "RAM Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_node_status_capacity_memory_bytes{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "This panel shows historical utilization for the node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name!=\"\",container_name!=\"POD\",pod_name!=\"\",instance=\"$node\"}[10m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=\"$node\"}) / sum(kube_node_status_capacity_cpu_cores{node=\"$node\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "This panel shows historical utilization for the node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "SUM(container_memory_usage_bytes{container_name!=\"\",pod_name!=\"\",instance=\"$node\"}) / SUM(kube_node_status_allocatable_memory_bytes{node=\"$node\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container!=\"\",container!=\"POD\",node=\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=\"$node\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Traffic in and out of this namespace, as a sum of the pods within it",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "<- in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Disk reads and writes for the namespace, as a sum of the pods within it",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "<- write"
    },
    {
     "expr": "- sum (rate (container_fs_reads_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "-> read"
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "format": "none",
     "valueName": "avg",
     "content": "graph LR\nA[Square Rect] -- Link text --> B((Circle))\nA --> C(Round Rect)\nB --> D{Rhombus}\nC --> D\n"
    }
   ]
  }
 ]
}
{
 "title": "Prediction",
 "time": { "from": "now-30m", "to": "now+30m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Managed Node",
    "query": "show tag values on alameda_cluster_status from node with key=\"name\""
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "show tag values on alameda_cluster_status from container with key=\"alameda_scaler_namespace\""
   },
   {
    "name": "scaler",
    "label": "Alameda Scaler",
    "query": "show tag values on alameda_cluster_status from container with key=\"alameda_scaler_name\" where \"alameda_scaler_namespace\" = '$ns'"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "show tag values on alameda_cluster_status from container with key=\"pod_name\" where \"alameda_scaler_namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler'"
   },
   {
    "name": "container",
    "label": "container",
    "query": "show tag values on alameda_cluster_status from container with key=\"name\" where \"alameda_scaler_namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and \"pod_name\" = '$pod'"
   }
  ]
 },
 "panels": [
  { "title": "Managed Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Managed Node",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from alameda_cluster_status..node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alameda Scalers",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select alameda_scaler_namespace as namespace, alameda_scaler_name as \"alameda scaler\", pod_name as pod, \"name\" as \"container\", node_name as node, \"policy\", is_alameda from alameda_cluster_status..container where is_alameda = true and is_deleted = false group by \"alameda_scaler_namespace\", \"alameda_scaler_name\", \"pod_name\", \"name\" order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Node Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Node CPU Usage: Observation and Prediction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Prediction: cpu_usage_seconds_percentage",
     "measurement": "node_prediction",
     "query": "select value from \"alameda_prediction\"..\"node\" where \"metric\" = 'cpu_usage_seconds_percentage' and \"name\" = '$node'  and \"is_scheduled\" = 'false' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "node",
       "operator": "=",
       "value": "ip-172-23-1-91.us-east-2.compute.internal"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpu" }
     ]
    },
    {
     "expr": "node:node_cpu_utilisation:avg1m{node=\"$node\"}",
     "legendFormat": "Observation: cpu_usage_seconds_percentage"
    }
   ]
  },
  {
   "title": "Node Memory Usage: Observation and Prediction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Prediction: memory_usage_bytes",
     "measurement": "node_prediction",
     "query": "select value from \"alameda_prediction\"..\"node\" where \"metric\" = 'memory_usage_bytes' and \"name\" = '$node' and \"is_scheduled\" = 'false' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "node",
       "operator": "=",
       "value": "ip-172-23-1-91.us-east-2.compute.internal"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpu" }
     ]
    },
    {
     "expr": "node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum{node=\"$node\"}",
     "legendFormat": "Observation: memory_usage_bytes"
    }
   ]
  },
  { "title": "Container Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Container CPU Usage: Observation and Prediction (in cpu core)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Prediction: cpu_usage_seconds_percentage",
     "measurement": "node_prediction",
     "query": "select value from \"alameda_prediction\"..\"container\" where \"metric\" = 'cpu_usage_seconds_percentage' and \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "node",
       "operator": "=",
       "value": "ip-172-23-1-91.us-east-2.compute.internal"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpu" }
     ]
    },
    {
     "expr": "namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$ns\", pod_name=\"$pod\", container_name=\"$container\"}",
     "legendFormat": "Observation : cpu_usage_seconds_percentage"
    }
   ]
  },
  {
   "title": "Container Memory Usage: Observation and Prediction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Prediction: memory_usage_bytes",
     "measurement": "node_prediction",
     "query": "select value from \"alameda_prediction\"..\"container\" where \"metric\" = 'memory_usage_bytes' and \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "node",
       "operator": "=",
       "value": "ip-172-23-1-91.us-east-2.compute.internal"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpu" }
     ]
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"$ns\", pod_name=\"$pod\", container_name=\"$container\"}",
     "legendFormat": "Observation: cpu_usage_seconds_percentage"
    }
   ]
  },
  { "title": "Recommendation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Container Resource Recommendations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "cpu limit (in cpu core)",
     "measurement": "node_prediction",
     "query": "select resource_limit_cpu from \"alameda_recommendation\"..\"container\" where \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "node",
       "operator": "=",
       "value": "ip-172-23-1-91.us-east-2.compute.internal"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpu" }
     ]
    },
    {
     "alias": "cpu request (in cpu core)",
     "measurement": "node_prediction",
     "query": "select resource_request_cpu from \"alameda_recommendation\"..\"container\" where \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "node",
       "operator": "=",
       "value": "ip-172-23-1-91.us-east-2.compute.internal"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpu" }
     ]
    },
    {
     "alias": "memory limit",
     "measurement": "node_prediction",
     "query": "select resource_limit_memory from \"alameda_recommendation\"..\"container\" where \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "node",
       "operator": "=",
       "value": "ip-172-23-1-91.us-east-2.compute.internal"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpu" }
     ]
    },
    {
     "alias": "memory request",
     "measurement": "node_prediction",
     "query": "select resource_request_memory from \"alameda_recommendation\"..\"container\" where \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "node",
       "operator": "=",
       "value": "ip-172-23-1-91.us-east-2.compute.internal"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpu" }
     ]
    }
   ]
  }
 ]
}